<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta charset="UTF-8"/><meta name="uuid" content="54e37503-abcc-4798-8058-d1d2a794b8c7"/><meta name="last-change-date" content="2022-04-07T19:07:36.8120000-6:00"/><meta name="create-date" content="2022-04-07T19:07:36.8120000-6:00"/><meta name="qrichtext" content="1" /><title>no-vowel-mark</title><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'DejaVu Sans'; font-size:10pt; font-weight:400; font-style:normal;">
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">src = open('source.txt' , encoding='UTF-8').read()</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">src = src.replace('ك','ک')<br />for x in src:<br />    if x not in {'ا','ب','پ','ت','ث','ج','چ','ح','خ','د','ذ','ر','ز','ژ','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ک','گ','ل','م','ن','و','ه','ی','آ','أ','إ','ؤ','ئ','ء','ٌ','ٍ','ً','ُ','ِ','َ','ّ',' '}:<br />        src = src.replace(x,' ')</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">splitted = src.split()<br />wordset = set(splitted)<br />rm = []<br />for x in wordset:<br />    if len(x) == 1 :<br />        rm.append(x)<br />    for z in ['ْ','ٌ','ٍ','ً','ُ','ِ','َ','ّ']:<br />        if z in x:<br />            rm.append(x)<br />rm = set(rm)<br />for x in rm:<br />    wordset.remove(x)</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">output = open('output.txt','w', encoding='UTF-8')</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">out = []<br />for x in wordset:<br />    out.append((x,splitted.count(x)))</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">def num(e):<br />    return e[1]<br />out.sort(reverse= True ,key= num)</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">n = 0<br />for x in out:<br />    output.write(&quot;\&quot;&quot; + str(list(out)[n][0]) + &quot;\&quot;&quot; + &quot;,&quot; + &quot;\n&quot;)<br />    n += 1<br /></p></body></html>